/**
 * Generates the `zeros()` lookup table for MerkleTreeWithHistory.
 *
 * The table is the hash of an all-empty subtree at each level. Tornado
 * hardcodes it because computing it on-chain would cost a MiMC call per level
 * on every deploy.
 *
 * It is generated rather than transcribed, and checked against Tornado's
 * published values, because a single wrong digit in this table produces a
 * contract that accepts merkle proofs the circuit never authorised — and it
 * would pass every casual test, since deposits and withdrawals would still
 * "work" against each other on the same wrong tree.
 *
 * ZERO_VALUE is deliberately kept as Tornado's keccak256("tornado") % FIELD.
 * It is only an empty-leaf placeholder with no security role, and reusing it
 * lets the whole MiMC pipeline be verified against known-good constants.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildMimcSponge } from 'circomlibjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEVELS = 32;

const ZERO_VALUE =
  21663839004416932945382355908790599225266501822907911457504978515578255421292n;

// Published Tornado Cash values. If our MiMC pipeline disagrees with these,
// something is wrong and nothing downstream can be trusted.
const KNOWN = {
  0: '0x2fe54c60d3acabf3343a35b6eba15db4821b340f76e741e2249685ed4899af6c',
  1: '0x256a6135777eee2fd26f54b8b7037a25439d5235caee224154186d2b8a52e31d',
  2: '0x1151949895e82ab19924de92c40a3d6f7bcb60d92b00504b8199613683f0c200',
  3: '0x20121ee811489ff8d61f09fb89e313f14959a0f28bb428a20dba6b0b068b3bdb',
};

const hex32 = (v) => '0x' + v.toString(16).padStart(64, '0');

async function main() {
  const mimc = await buildMimcSponge();
  const hashLeftRight = (l, r) =>
    BigInt(mimc.F.toString(mimc.multiHash([l, r], 0n, 1)));

  const zeros = [ZERO_VALUE];
  for (let i = 1; i < LEVELS; i++) {
    zeros.push(hashLeftRight(zeros[i - 1], zeros[i - 1]));
  }

  let failures = 0;
  for (const [i, expected] of Object.entries(KNOWN)) {
    const got = hex32(zeros[Number(i)]);
    const ok = got === expected;
    if (!ok) failures++;
    console.log(`  zeros(${i}) ${ok ? '✓' : '✗ MISMATCH'}`);
    if (!ok) {
      console.log(`    expected ${expected}`);
      console.log(`    got      ${got}`);
    }
  }
  if (failures) throw new Error(`${failures} zeros() value(s) disagree with Tornado`);
  console.log(`\n  all ${Object.keys(KNOWN).length} known values match\n`);

  const cases = zeros
    .map((z, i) => `        if (i == ${i}) return bytes32(uint256(${hex32(z)}));`)
    .join('\n');

  const sol = `// SPDX-License-Identifier: MIT
// GENERATED FILE — do not edit. Run: npm run gen:zeros
pragma solidity ^0.8.24;

/// @notice Hash of an all-empty subtree at each level.
/// @dev Generated by scripts/genZeros.mjs and checked against Tornado Cash's
///      published constants. Regenerate rather than hand-edit.
abstract contract MerkleTreeZeros {
    function zeros(uint256 i) public pure returns (bytes32) {
${cases}
        revert("index out of bounds");
    }
}
`;

  const out = path.join(ROOT, 'contracts', 'MerkleTreeZeros.sol');
  await writeFile(out, sol);
  console.log(`  wrote ${path.relative(ROOT, out)} (${LEVELS} levels)`);
}

main().then(
  () => process.exit(0),
  (e) => {
    console.error(e.message);
    process.exit(1);
  },
);
